name: CICD RELEASE PIPELINE

on:
  push:
    branches:
      - "main"

jobs:

  buildpush:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
    
      - name: Set environment variables
        env:
          BETA_ACCOUNT_ENV_FILE: ${{ secrets.BETA_ACCOUNT_ENV_FILE }}
        run: |
          if [ -d /home/runner/work/account/account/config/ ]; then
            echo "Directory already exists, skipping creation."
          else
            mkdir /home/runner/work/account/account/config/
            echo "Directory created."
          fi
          echo $BETA_ACCOUNT_ENV_FILE | base64 --decode >> /home/runner/work/account/account/config/app.yaml
          echo "${BETA_ACCOUNT_ENV_FILE}"
          ls -l

      - name: Create SHA Container Tag
        id: sha_tag
        run: |
          tag=$(cut -c 1-7 <<< $GITHUB_SHA)
          echo "::set-output name=tag::$tag"

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
          
      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}

      - name: Build and push
        uses: docker/build-push-action@v4
        with:
          context: .
          file: ./Dockerfile
          platforms: linux/amd64
          push: true
          tags: |
            ${{ secrets.DOCKER_BETA_ACCOUNT_REPOSITORY }}:latest
            ${{ secrets.DOCKER_BETA_ACCOUNT_REPOSITORY }}:${{ github.ref_name }}-${{ steps.sha_tag.outputs.tag }}
          build-args: |
            git_sha=${{ github.sha }}

      - name: Check if Tag Exists
        id: check_tag
        run: |
          tag_name="${{ github.ref_name }}-${{ steps.sha_tag.outputs.tag }}"
          existing_tag=$(git tag --list $tag_name)
          if [ -n "$existing_tag" ]; then
            echo "::set-output name=tag_exists::true"
          else
            echo "::set-output name=tag_exists::false"
          fi

      - name: Create Release
        if: github.ref == 'refs/heads/preprod' && steps.check_tag.outputs.tag_exists != 'true'
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GIT_TOKEN }}
        with:
          tag_name: ${{ github.ref_name }}-${{ steps.sha_tag.outputs.tag }}
          release_name: ${{ github.ref_name }}-${{ steps.sha_tag.outputs.tag }}
          prerelease: true

      - name: remote ssh commands using key
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST_PROD }}
          username: ${{ secrets.USERNAME }}
          password: ${{ secrets.SSH_PASS_PROD }}
          port: ${{ secrets.PORT }}
          script: |
            whoami
            ls -al
            docker pull ${{ secrets.DOCKER_BETA_ACCOUNT_REPOSITORY }}:${{ github.ref_name }}-${{ steps.sha_tag.outputs.tag }}
            ls -l
            cd pipelinev2
            ls -l
            if [ -d "${{ github.event.repository.name }}" ]; then
              echo "Directory already exists, skipping creation."
            else
              mkdir "${{ github.event.repository.name }}"
              echo "Directory created."
            fi
            cd ${{ github.event.repository.name }}
            if [ ! -d "${{ secrets.PATH_LOG_ACCOUNT }}" ]; then
              mkdir -p ${{ secrets.PATH_LOG_ACCOUNT }}
            fi
            cat <<EOF > docker-compose.yml
            services:
              backend:
                image: ${{ secrets.DOCKER_BETA_ACCOUNT_REPOSITORY }}:${{ github.ref_name }}-${{ steps.sha_tag.outputs.tag }}
                ports:
                  - "8010-8011:8010"
                deploy:
                  mode: replicated
                  replicas: 2
                  restart_policy:
                    condition: on-failure
                    delay: 5s
                    max_attempts: 3
                    window: 120s
                volumes:
                  - ${{ secrets.PATH_LOG_ACCOUNT }}:/app2/log/  
            EOF
            docker compose rm -f
            docker compose pull
            docker compose up --build -d