name: Terraform Plan and Budgeting

on:
  pull_request:
    branches:
        - terraform    
  push:
    branches:
        - terraform    

jobs:
  plan:
    runs-on: ubuntu-latest
    name: Terraform plan
    env:
      DIGITALOCEAN_TOKEN: ${{ secrets.DIGITALOCEAN_TOKEN }}
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Terraform init
        run: terraform init

      - name: Terraform plan
        run: terraform plan